#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99
boot() {
	# process user commands
	/usr/sbin/ff-offline-ssid.sh 60 > /dev/null
	[ -f /etc/freifunk/start.ebtables ]  && sh /etc/freifunk/start.ebtables
}
