#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99
boot() {
	# process user commands
	sh /usr/sbin/ff-offline-ssid.sh 60
	[ -f /etc/freifunk/start.ebtables ]  && sh /etc/freifunk/start.ebtables
	sh /usr/sbin/ff-offline-ssid.sh 60
}
